### ISSUE TITLE
aria2c 19.3 fails to build on Mac OS X 10.11.3 El Capitan

### ISSUE THREAD

**Issue by mario-grgic** [tatsuhiro-t/aria2#562]
Note that it builds fine on OS X 10.9.5.

Here is the make error report:

In file included from a2gmp.cc:35:
In file included from ./a2gmp.h:38:
In file included from /usr/local/include/gmp.h:51:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstddef:46:9: error: no member named
      'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
1 error generated.
make[3]: *** [a2gmp.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by mario-grgic** [comment]
This goes away after I upgraded GMP to version 6.1
